### ISSUE TITLE
Better Error Checking

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1022]
<img width="1512" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/3647e919-aab7-4d21-ad48-57602c640809">

- The above results when you enter an invalid url `/forms/judges` which is not valid but instead if shoes a complicated error message
- Need to check the error checking and make sure it shows a 404 page as expected

**Comment by JohnZ9865** [comment]
It already shows 404 page as expected:
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/72993c6b-3d89-4074-b73c-e8a084b81571)
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/b9c78350-d904-4a89-9204-9e298d72b587)

Code shows normal error message:
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/c03fecd1-c196-4896-b18a-450ad780caf3)
