### ISSUE TITLE
Explore Curved Edges

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#106]
![image](https://github.com/acm-ucr/hackathon-website/assets/36285610/0ba53168-9a2e-4528-a2e1-87532142a80b)

- Try to curve the edges on the QR code, if it doesn't work, then close the issue

**Comment by rfairooz** [comment]
I tried looking more into it and seems like styling of any sort is not working on qr.react. Other options I learned were with qr-image for nodejs and maybe making a custom QR code. I tried out qr-image but same issue doesn't curve the edges. And I doubt custom making just to curve edges is the best thing. Imma close this then
