### ISSUE TITLE
Change Text

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#112]
![image](https://github.com/acm-ucr/hackathon-website/assets/36285610/ec22763a-b451-4201-855c-4cece2a589b9)

- Change it to show the current time with hours, minutes, seconds
- This prevents people from screenshotting the page and using it multiple times

**Comment by torisutansan02** [comment]
Hey Shah, do you know which page routes me to this? Is this a change I should make on the sign in page?

**Comment by shahdivyank** [comment]
> Hey Shah, do you know which page routes me to this? Is this a change I should make on the sign in page?

/user/checkin
