### ISSUE TITLE
Hackpack: `nextjs-hackpack`

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1133]
- Generate from ACM UCR Website template 
- Update readme to describe the codebase and how to get started
- Update this new repo as a template repo
- Comment a link to the repo and report to Divyank and we can close the issue

**Comment by seanquiambao** [comment]
https://github.com/acm-ucr/nextjs-hackpack

**Comment by shahdivyank** [comment]
Good to go!
