### ISSUE TITLE
Hackpack: `python-hackpack`

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1134]
- build using poetry
- empty repo with sample hello world
- need build/run scripts working
- need 2 files (ie main and helper) to ensure multi file system is working
- Update readme to describe the codebase and how to get started
- Update this new repo as a template repo
- Comment a link to the repo and report to Divyank and we can close the issue

**Comment by SafeDuck** [comment]
https://github.com/acm-ucr/python_hackpack
