### ISSUE TITLE
Uniform Button Spacing

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1177]
<img width="1329" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/a48205ab-5107-44a1-943f-deb066b32bbc">

- Ensure all buttons have uniform spacing

**Comment by swooshoo** [comment]
you're referring to the generate reset view buttons right? 

do you wan tthe right side professor/industry/student buttons uniform too?
