### ISSUE TITLE
Add Padding

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1355]
<img width="1512" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/182069fd-323c-4018-a00a-420b033d45e7">

- Form should not be touching the end of the page
- Add padding so that form sits higher than the bottom of the page

**Comment by kathalinne** [comment]
It seems like the most updated code I pulled already fixed this issue. It was fixed by someone adding py-5 in Form.jsx. Although I can move the form higher if needed.
