### ISSUE TITLE
Simplify Words

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1358]
<img width="473" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/f4e0feb5-1414-4f4f-9175-5f8d3ea00469">

- Remove secondary and keep just high school in both less than HS and HS
- Remove University from Undergrad and Grad
-

**Comment by FireHeart003** [comment]
Hello! Nice to meet you! By any chance would I be Able to be added as a contributor? I am working on contributing to open source projects for a college class I am taking. Much appreciated!
