### ISSUE TITLE
Update Packing List 

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1385]
<img width="675" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/e0698cb5-dd8c-4047-95db-4e57764e565b">

<img width="1512" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/c49a2832-7048-4254-92b6-eb0ec220a58f">

- need our packing list to be more comprehensive for those who might be away from home for the weekend
- Refer to Stanfords Tree Hacks packing list for inspiration

**Comment by MightyMango1** [comment]
Are the items highlighted in green from TreeHack required in our hackathon? (Should I be including it in the packing list)
Will there be a shower for hackers to use?
