### ISSUE TITLE
Fix Up Images

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1404]
<img width="324" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/201a5e1c-6604-4c18-9655-98347f70485d">

- UCRLogo is not being used anymore and can be deleted
- The other images might be outdated, check in with every hackathon to get a more recent photo

**Comment by mnyamunda-scottlogic** [comment]
Hi, I hope you are well. I would like to pick up this issue if possible :)
