### ISSUE TITLE
Update Navigation

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1478]
<img width="134" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/50eb2b03-0fe1-4782-a78c-d9b15498ca48">

- Due to the high number of links we have, some of them can be condensed into icons
- Discord, Devpost, Website, Feedback Form, Signout should all be icons

**Comment by Taahh** [comment]
A few questions for this:
a) Do we want the icons to be close by like in the image shown or spaced out?
![image](https://github.com/acm-ucr/hackathon-website/assets/9047036/ace7ae33-c65e-4241-bd7e-f463f632e238)
This is how I currently have it on my version
b) Do we want tooltips to be displayed when hovering over the item so users know what each icon does?
