### ISSUE TITLE
Reduce Gap

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1587]
<img width="386" alt="image" src="https://github.com/user-attachments/assets/42667fec-f179-4d8b-af40-191f83523ca8">

- there is a bit too much gap :sob:

**Comment by Derrick-Mao** [comment]
![image](https://github.com/user-attachments/assets/39b839b4-ce88-4ac5-9823-9d4eb9aa7762)
space-x-8 to space-x-4
