### ISSUE TITLE
Migrate to Shadcn Badges

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1786]
<img width="220" alt="image" src="https://github.com/user-attachments/assets/68010634-3846-4dc1-add6-bba5c215fcb9">

- Change to shadcn badges

**Comment by Derrick-Mao** [comment]
Error: Tag component's Badge does not reflect mb-2 passed in as classes from form/status,
because the m-0 in Badge's className is overriding the mb-2.
Two options:
1. move ${classes} to the end of Badge className so its applied after m-0
2. delete m-0 from Badge className
