### ISSUE TITLE
Add No Teams Available

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1889]
![image](https://github.com/user-attachments/assets/a5738e5a-7a13-4283-9f2e-d0df3032f268)

- if no teams are available then show that a message accordingly

**Comment by JohnZ9865** [comment]
already done. 
<img width="560" alt="image" src="https://github.com/user-attachments/assets/c5c92f5f-81b8-4c7a-90f6-7d0e19828dcc" />
