### ISSUE TITLE
Extract Register Data

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#251]
Within the register form, there is static data that will change between hackathons and we want an easy interface to work with them 
<img width="554" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/3cdf1b19-6d27-4812-80d1-3c1d83258a9c">

- Create a Register.jsx file under the data folder which holds such static information

**Comment by twang0323** [comment]
not quite sure what the instruction is asking for, is it like this?
![image](https://github.com/acm-ucr/hackathon-website/assets/122486013/af86621c-ae8d-49b3-ba0b-1ca8296145a4)
