### ISSUE TITLE
Limit Height

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#263]
<img width="1079" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/a4d268f1-a171-4351-82e2-9af905f1a125">

- Due to the sheer number of schools, there needs to be a limit on how tall the component is before you scroll through the results 
- Set a height and ensure it does not exceed the bottom of the screen so the user can scroll through the results instead

**Comment by rfairooz** [comment]
Dropdown height was all taken care of in another issue.
