### ISSUE TITLE
Add Following Affiliations

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#324]
<img width="1309" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/af959b3f-8f50-461b-92f9-31497aca5487">

- We need to account for all types of affiliations, including the following: 
- director, marketing, operations, sponsorship, recruitment, software, uiux, recruitment

**Comment by twang0323** [comment]
recruitment is doubled
