### ISSUE TITLE
Add Proper Affiliations

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#358]
<img width="518" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/6db09d81-b04f-456e-8566-3bd1923604d6">

- Add all team affiliations + activities + workshops + general

**Comment by twang0323** [comment]
director, marketing, operations, sponsorship, recruitment, software, uiux + activities + workshops + general, is this all the affiliations need to add to calender?

**Comment by menthy-wu** [comment]
Yea, you can just do these for now
