### ISSUE TITLE
Change Page Title to Judges

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#386]
<img width="1147" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/a94db73c-fe64-48da-89a8-78ddc70ae4bc">

- Rename Judging to Judges

**Comment by AnjalineSingh** [comment]
<img width="1038" alt="Screen Shot 2023-08-28 at 2 53 29 PM" src="https://github.com/acm-ucr/hackathon-website/assets/117554632/a5364a2a-1e62-4f30-9017-ea2233055d24">
