### ISSUE TITLE
Change to Pending, Confirmed, Not Attending

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#539]
![image](https://github.com/acm-ucr/hackathon-website/assets/36285610/2cbeb599-6fb2-4fec-9bce-b17b00317a79)

- More consistent with other pages

**Comment by sophiiiapapaya** [comment]
@shahdivyank Were you referring to the status tags?

**Comment by sophiiiapapaya** [comment]
<img width="680" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/102562264/c188f86b-db8d-429b-bdbd-b1a665089f5e">
I made changes to the filter and the buttons next to the checkbox as in the image.
