### ISSUE TITLE
Convert To String in Backend

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#739]
<img width="280" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/6f23faeb-a61c-4ceb-92f2-e67bbd019bc4">

- Currently we read the data as an array and process it as an array, instead we should make it a string that is comma separated and do this formatting in the backend, instead of reading an array it will read a string

**Comment by NovaSagittarii** [comment]
Isn't a stringified JSON array already csv?

**Comment by shahdivyank** [comment]
CSV has nothing to do with this. The data comes in as an array to the data table, which is unneeded, you can just send it in as a string with join called on it
