### ISSUE TITLE
User Dashboard Team Display Mobile

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/aurora#918]
- if you go to /user/dashboard on mobile, the team section is cutting off

<img width="425" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/73259022/87fb6a1d-d251-4f91-a86f-bbf266045e19">

**Comment by JohnZ9865** [comment]
I think there's something wrong with users, it's expecting diet as an element but it doesn't exist (at least for my profile)
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/2a2dbac7-df60-433d-8c8e-f71bf975e57f)

![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/9df077d4-3c62-40a1-b7b9-f94d49894448)

**Comment by JohnZ9865** [comment]
I think there's something wrong with user.session, this occurs when trying to access user/dashboard/.
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/80e62ebd-7419-40d6-b952-ac56571558de)
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/5219b664-ae6b-462f-8798-d2c4d35de30d)


Its supposed to have diet as an attribute but it doesn't.
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/4d264b05-9e03-4dfa-994f-338abfc88241)

The user comes from line 22. Before that it came from useSession hook of nextJS.
![image](https://github.com/acm-ucr/hackathon-website/assets/64669569/c6b76445-ba14-482d-b57f-a8fe39a823b0)
