### ISSUE TITLE
Display Team Table

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#997]
<img width="836" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/9d4d2a85-bfbc-4fe7-8282-038fb47071e8">

- Currently it shows the team name (which does not exist anymore), and showing the name or uid is pointless since judges do not know the teams by heart
- Need to show the team table numbers

**Comment by pondohoo** [comment]
(two digits) table number: team name

not for judges
